print("Bienvenido sl convertor de grados celsius a grados farenheit")
grados_farenheit = int(input("¿Cuantos grados farenheit quieres pasar a centigrados?"))
grados_celsius = ((grados_farenheit - 32)/1.8)
print("{} grados farenheit".format(grados_farenheit), "son igual a {} grados celsius".format(grados_celsius)
      )
